/* Application bootstrap. Loaded before router.js, after every view script.
   Each page (/, /new-eden/, /exordium/, /faq/) is a real subpage shipping
   this same shell with every panel already in the DOM (see index.html) —
   only one is shown at a time. <body data-tab="..."> names the view the
   page shows on first load. router.js intercepts nav clicks after that and calls
   runTab() directly instead of letting the browser navigate, so board
   switches never reload the page; a real navigation (JS disabled, crawler,
   direct link) still lands on the matching static subpage generated by
   tools/build_pages.py. */
"use strict";

/* FAQ is static markup already in the DOM (no ESI data) — a no-op view so
   App can treat it exactly like the jobs boards. */
const FaqView = {
  load: async () => {},
  render() {},
  prefetchDetails: async () => {},
  prefetchPrices: async () => {}
};

/* The entry point to both boards: a ranked "grab this now" list, not a
   stats report. Loads both boards in parallel (not sequentially) so landing
   on the dashboard first never takes longer than the slower of the two —
   and once loaded, NewEdenJobsView/ExordiumJobsView don't re-fetch when
   their own tab is opened afterward (see jobs.js's `hasLoaded` guard). */
const DashboardView = (() => {
  const $ = (id) => document.getElementById(id);
  const TOP_N = 8;

  async function load(force = false) {
    await Promise.all([NewEdenJobsView.load(force), ExordiumJobsView.load(force)]);
  }

  function dealValueHtml(ratio) {
    if (ratio == null) return `<span class="status-pill dim">—</span>`;
    const cls = ratio < 0.9 ? "hot" : ratio > 1.1 ? "good" : "dim";
    return `<span class="status-pill ${cls}">${Math.round(ratio * 100)}%</span>`;
  }

  function dealExpandHtml(d) {
    const progress = d.progress ? `${fmtNum(d.progress.current)} / ${fmtNum(d.progress.desired)}` : "—";
    return `
      <div class="deal-expand">
        <b>${t("th_location")}:</b> ${d.locationName ? esc(d.locationName) : "—"}
        &middot; <b>${t("th_progress")}:</b> ${progress}
        &middot; <b>${t("th_expires")}:</b> ${fmtDate(d.expires)}<br>
        <b>${t("job_creator")}:</b> ${d.creatorName ? esc(d.creatorName) : "—"}
      </div>
    `;
  }

  /* Rows expand in place (full location/progress/expiry/creator) instead of
     linking off to the general board page — a click should answer "what is
     this job", not just relocate you. Bound once on the container; survives
     every re-render since only its children (not the container itself) are
     replaced. */
  function bindDealsClickOnce() {
    const list = $("dash-deals");
    if (list.dataset.bound) return;
    list.dataset.bound = "1";
    list.addEventListener("click", (e) => {
      const row = e.target.closest(".deal-row");
      if (!row) return;
      const expand = row.nextElementSibling;
      if (expand && expand.classList.contains("deal-expand")) expand.classList.toggle("open");
    });
  }

  function skeletonRows(n, cls) {
    return Array.from({ length: n }, () => `<div class="skeleton ${cls}"></div>`).join("");
  }

  function renderDeals(deals) {
    bindDealsClickOnce();
    const list = $("dash-deals");
    if (deals.length === 0) {
      list.innerHTML = skeletonRows(TOP_N, "skeleton-row");
      return;
    }
    list.innerHTML = deals.map(d => {
      const sub = d.method ? `${d.boardLabel} · ${esc(jobMethodLabel(d.method))}` : d.boardLabel;
      return `
        <div class="deal-row">
          <span class="deal-name">${esc(d.name)}<span class="sub">${sub}</span></span>
          <span class="deal-reward mono">${fmtIsk(d.reward)} ISK</span>
          ${dealValueHtml(d.ratio)}
        </div>
        ${dealExpandHtml(d)}
      `;
    }).join("");
  }

  function renderSecurity(counts) {
    const bar = $("dash-secbar");
    const legend = $("dash-seclegend");
    const total = counts.hs + counts.ls + counts.ns;
    if (total === 0) {
      bar.innerHTML = `<div class="skeleton skeleton-bar" style="flex:1;margin:0"></div>`;
      legend.innerHTML = "";
      return;
    }
    bar.innerHTML = ["hs", "ls", "ns"].map(cls => {
      const pct = Math.round((counts[cls] / total) * 100);
      if (pct <= 0) return "";
      /* A narrow sliver can't fit its own "N%" label without overlapping the
         next segment — drop the label below a threshold, keep the tooltip. */
      const label = pct >= 8 ? `${pct}%` : "";
      return `<div class="sec-${cls}" style="flex:${counts[cls]}" title="${pct}%">${label}</div>`;
    }).join("");
    legend.innerHTML = `
      <span class="leg-hs">${t("dash_sec_hs")}</span>
      <span class="leg-ls">${t("dash_sec_ls")}</span>
      <span class="leg-ns">${t("dash_sec_ns")}</span>
    `;
  }

  function renderCorps(corps) {
    const list = $("dash-corps");
    if (corps.length === 0) {
      list.innerHTML = skeletonRows(5, "skeleton-row");
      return;
    }
    const max = corps[0].count;
    list.innerHTML = corps.map((c, i) => `
      <div class="corp-row">
        <span class="rank mono">${i + 1}</span>
        <span class="cname">${esc(c.name)}</span>
        <span class="bar" style="width:${Math.max(8, Math.round((c.count / max) * 120))}px"></span>
        <span class="count mono">${t("dash_jobs_count", { count: c.count })}</span>
      </div>
    `).join("");
  }

  function render() {
    const main = NewEdenJobsView.stats();
    const exo = ExordiumJobsView.stats();

    const priceableCount = main.priceableCount + exo.priceableCount;
    const belowMarketCount = main.belowMarketCount + exo.belowMarketCount;
    $("dash-active").textContent = fmtNum(main.count + exo.count);
    $("dash-isk").textContent = fmtIsk(main.totalReward + exo.totalReward) + " ISK";
    $("dash-below").textContent = priceableCount > 0 ? Math.round((belowMarketCount / priceableCount) * 100) + "%" : t("dash_pending");

    const deals = [
      ...NewEdenJobsView.topPayouts(TOP_N).map(j => ({ ...j, boardLabel: t("nav_new_eden") })),
      ...ExordiumJobsView.topPayouts(TOP_N).map(j => ({ ...j, boardLabel: t("nav_exordium") }))
    ].sort((a, b) => b.reward - a.reward).slice(0, TOP_N);
    renderDeals(deals);

    const secMain = NewEdenJobsView.securityBreakdown();
    const secExo = ExordiumJobsView.securityBreakdown();
    renderSecurity({
      hs: secMain.hs + secExo.hs,
      ls: secMain.ls + secExo.ls,
      ns: secMain.ns + secExo.ns
    });

    const corpCounts = new Map();
    for (const c of [...NewEdenJobsView.topCorps(50), ...ExordiumJobsView.topCorps(50)]) {
      corpCounts.set(c.name, (corpCounts.get(c.name) ?? 0) + c.count);
    }
    const topCorps = [...corpCounts.entries()]
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 5);
    renderCorps(topCorps);

    $("dash-neweden-count").textContent = fmtNum(main.count);
    $("dash-neweden-isk").textContent = fmtIsk(main.totalReward) + " ISK";
    $("dash-exordium-count").textContent = fmtNum(exo.count);
    $("dash-exordium-isk").textContent = fmtIsk(exo.totalReward) + " ISK";
  }

  async function prefetchDetails(onProgress) {
    await Promise.all([
      NewEdenJobsView.prefetchDetails(onProgress),
      ExordiumJobsView.prefetchDetails(onProgress)
    ]);
  }

  async function prefetchPrices(onProgress) {
    await Promise.all([
      NewEdenJobsView.prefetchPrices(onProgress),
      ExordiumJobsView.prefetchPrices(onProgress)
    ]);
  }

  return { load, render, prefetchDetails, prefetchPrices };
})();

const App = (() => {
  const TABS = {
    dashboard: { view: DashboardView,   panel: "panel-dashboard" },
    "new-eden": { view: NewEdenJobsView, panel: "panel-new-eden" },
    exordium:   { view: ExordiumJobsView, panel: "panel-exordium" },
    faq:        { view: FaqView,          panel: "panel-faq" }
  };

  let activeTab = "dashboard";
  const loaded = new Set();
  let autoTimer = null;
  let lastUpdated = null;

  const $ = (id) => document.getElementById(id);

  function renderTimestamp() {
    if (!lastUpdated) return;
    $("timestamp").textContent = t("ts_label") + " " + lastUpdated.toLocaleTimeString("en-US");
  }

  function showPanel(tabId) {
    for (const [id, tab] of Object.entries(TABS)) {
      $(tab.panel).classList.toggle("hidden", id !== tabId);
      $("tab-" + id).classList.toggle("active", id === tabId);
    }
  }

  function setStatus(state, message = "") {
    $("error").classList.toggle("hidden", state !== "error");
    if (state === "error") $("error").textContent = message;
  }

  function reportError(err) {
    const hint = err && err.rateLimited ? t("err_rate_limit") : t("err_hint");
    setStatus("error", t("err_prefix") + (err?.message ?? err) + " — " + hint);
  }

  /* Background enrichment (per-job detail, then Jita/Manifest prices) — runs
     after the base list is already on screen, so it never blocks the
     initial render. A rate limit here just stops enrichment early; the base
     board stays usable. No-op for FaqView. */
  async function enrich(view) {
    try {
      await view.prefetchDetails((done, total) => {
        if (done % 10 === 0 || done === total) view.render();
      });
      view.render();
      await view.prefetchPrices((done, total) => {
        if (done % 5 === 0 || done === total) view.render();
      });
      view.render();
    } catch (err) {
      view.render();
      if (!err.rateLimited) reportError(err);
    }
  }

  async function runTab(tabId, force = false) {
    activeTab = tabId;
    showPanel(tabId);
    setStatus("idle"); // clear any error left over from a previous tab
    const tab = TABS[tabId];

    if (loaded.has(tabId) && !force) {
      tab.view.render();
      return;
    }

    try {
      await tab.view.load(force);
      loaded.add(tabId);
      tab.view.render();
      lastUpdated = new Date();
      renderTimestamp();
      setStatus("idle");
      enrich(tab.view);
    } catch (err) {
      reportError(err);
    }
  }

  /* Button label names what clicking switches *to*, not the current state —
     "Light mode" while dark is active, "Dark mode" once light is active. */
  function setTheme(theme) {
    document.documentElement.dataset.theme = theme;
    localStorage.setItem("fjb_theme", theme);
    $("theme-toggle").textContent = theme === "dark" ? t("theme_light") : t("theme_dark");
  }

  function setAutoRefresh(on) {
    localStorage.setItem("fjb_auto_refresh", on ? "1" : "0");
    $("auto-refresh").classList.toggle("active-mode", on);
    if (autoTimer) clearInterval(autoTimer);
    autoTimer = on
      ? setInterval(() => {
          loaded.delete(activeTab);
          runTab(activeTab, true);
        }, CONFIG.AUTO_REFRESH_MS)
      : null;
  }

  function init() {
    $("refresh").addEventListener("click", () => {
      loaded.delete(activeTab);
      runTab(activeTab, true);
    });
    $("auto-refresh").addEventListener("click", () => setAutoRefresh(!autoTimer));
    setAutoRefresh(localStorage.getItem("fjb_auto_refresh") === "1");

    $("theme-toggle").addEventListener("click", () => {
      setTheme(document.documentElement.dataset.theme === "light" ? "dark" : "light");
    });
    setTheme(localStorage.getItem("fjb_theme") || "dark");

    applyI18n();
    const pageTab = document.body.dataset.tab;
    runTab(TABS[pageTab] ? pageTab : "dashboard");
  }

  return { init, runTab, reportError };
})();

document.addEventListener("DOMContentLoaded", App.init);
