/* Application bootstrap. Loaded before router.js, after every view script.
   Each page (/, /new-eden/, /exordium/, /faq/) is a real subpage shipping
   this same shell with every panel already in the DOM (see src/page.html) —
   only one is shown at a time. <body data-tab="..."> names the view the
   page shows on first load. router.js intercepts nav clicks after that and calls
   runTab() directly instead of letting the browser navigate, so board
   switches never reload the page; a real navigation (JS disabled, crawler,
   direct link) still lands on the matching static subpage generated by
   tools/build_pages.py. */
"use strict";

/* FAQ is static markup already in the DOM (no ESI data) — a no-op view so
   App can treat it exactly like the jobs boards. */
const FaqView = {
  load: async () => {},
  render() {},
  prefetchDetails: async () => {},
  prefetchPrices: async () => {}
};

/* The entry point to both boards. On top the security ladder: every open
   job as one square, in the column of its broadcast system's security
   status, coloured as the game client colours that status. Below it the
   best paid jobs and who posts them. Loads both boards in parallel, so the
   overview never takes longer than the slower of the two, and the boards
   don't fetch again when opened afterwards (jobs.js, `hasLoaded`). */
const DashboardView = (() => {
  const $ = (id) => document.getElementById(id);
  const TOP_N = 12;
  const BINS = ["10", "9", "8", "7", "6", "5", "4", "3", "2", "1", "ns", "wh", "none"];
  let ladderDrawn = false;

  async function load(force = false) {
    await Promise.all([NewEdenJobsView.load(force), ExordiumJobsView.load(force)]);
  }

  /* The best paid jobs of both boards in one table, built from the same
     cells as the boards. A click opens the detail in place. */
  function renderDeals(deals) {
    const body = $("dash-deals");
    if (deals.length === 0) {
      body.innerHTML = Array.from({ length: TOP_N }, () => `<tr class="skeleton-row"><td></td><td></td><td></td><td></td><td></td></tr>`).join("");
      return;
    }
    body.innerHTML = deals.map(d => `<tr class="job-row" data-id="${esc(d.id)}" data-board="${d.board}" tabindex="0">${d.html}</tr>`).join("");
    if (!body.dataset.bound) {
      body.dataset.bound = "1";
      const open = (row) => {
        const view = row.dataset.board === "exordium" ? ExordiumJobsView : NewEdenJobsView;
        view.toggleDetail(row, row.dataset.id);
      };
      body.addEventListener("click", (e) => {
        const row = e.target.closest("tr.job-row");
        if (row) open(row);
      });
      body.addEventListener("keydown", (e) => {
        const row = e.target.closest("tr.job-row");
        if (!row || (e.key !== "Enter" && e.key !== " ")) return;
        e.preventDefault();
        open(row);
      });
    }
  }

  /* Square size: the largest that lets the fullest column fit the fixed
     height of the chart, the same for every column so area stays count.
     The chart's height never depends on the data, so nothing below it
     moves when the squares arrive. */
  function sizeLadder() {
    const ladder = $("ladder");
    const boxes = [...ladder.querySelectorAll(".sq")];
    const max = Math.max(1, ...boxes.map(b => b.querySelectorAll("i").length));
    /* Columns on a wide screen (count on its own line above the stack),
       rows on a phone (count after the last square). */
    const rows = getComputedStyle(ladder).getPropertyValue("--rows").trim() === "1";
    const label = 22;
    const W = Math.min(...boxes.map(b => rows ? b.clientWidth - 32 : b.parentElement.clientWidth));
    const H = boxes[0].clientHeight - (rows ? 0 : label);
    let pick = { s: 2, g: 1, per: Math.max(1, Math.floor((W + 1) / 3)) };
    for (let s = 14; s >= 3; s--) {
      const g = s >= 8 ? 2 : 1;
      const per = Math.max(1, Math.floor((W + g) / (s + g)));
      if (Math.ceil(max / per) * (s + g) - g <= H) { pick = { s, g, per }; break; }
    }
    ladder.style.setProperty("--s", pick.s + "px");
    ladder.style.setProperty("--g", pick.g + "px");
    ladder.style.setProperty("--per", pick.per);
  }

  function renderLadder(counts) {
    if (!counts) return;
    const ladder = $("ladder");
    const animate = !ladderDrawn && !matchMedia("(prefers-reduced-motion: reduce)").matches;
    BINS.forEach((bin, i) => {
      const n = counts[bin] ?? 0;
      /* The count rides on top of its stack (wrap-reverse puts the last
         child on the top line). */
      $("bin-" + bin).innerHTML = "<i></i>".repeat(n) + `<b>${fmtNum(n)}</b>`;
      const label = bin === "wh" ? t("ladder_wh", { n: fmtNum(n) })
        : bin === "none" ? t("ladder_none", { n: fmtNum(n) })
        : t("ladder_bin", { sec: bin === "ns" ? "\u22640.0" : fmtSec(Number(bin) / 10), n: fmtNum(n) });
      $("sr-" + bin).textContent = label;
      ladder.querySelector(`[data-bin="${bin}"]`).style.setProperty("--i", i);
    });
    sizeLadder();
    if (!ladderDrawn) {
      ladderDrawn = true;
      new ResizeObserver(sizeLadder).observe(ladder);
      if (animate) {
        ladder.classList.add("enter");
        setTimeout(() => ladder.classList.remove("enter"), 1400);
      }
    }
    ladder.setAttribute("aria-busy", "false");
  }

  function renderCorps(corps) {
    const list = $("dash-corps");
    list.innerHTML = corps.map(c => `<li><span class="cname">${esc(c.name)}</span><span class="n">${fmtNum(c.count)}</span></li>`).join("");
  }

  function render() {
    /* The totals count every job once. A job broadcast from both sides of
       the Exordium gap appears on both boards (31 of 383 on 5.10.2026), so
       Exordium only contributes the jobs New Eden doesn't already have.
       The two board rows keep their own full counts: that is what each
       board shows. */
    const mainIds = NewEdenJobsView.scopedIds();
    const main = NewEdenJobsView.stats();
    const exoOnly = ExordiumJobsView.stats(mainIds);

    const priceable = main.priceableCount + exoOnly.priceableCount;
    const below = main.belowMarketCount + exoOnly.belowMarketCount;
    $("deals-note").textContent = priceable > 0 && NewEdenJobsView.ladder()
      ? t("deals_note", { pct: fmtPct(below / priceable) })
      : t("deals_note_pending");

    const deals = [
      ...NewEdenJobsView.topPayouts(TOP_N).map(j => ({ ...j, board: "main" })),
      ...ExordiumJobsView.topPayouts(TOP_N, mainIds).map(j => ({ ...j, board: "exordium" }))
    ].sort((a, b) => b.reward - a.reward).slice(0, TOP_N);
    renderDeals(deals);

    const lMain = NewEdenJobsView.ladder();
    const lExo = ExordiumJobsView.ladder(mainIds);
    if (lMain && lExo) {
      const sum = {};
      for (const bin of BINS) sum[bin] = (lMain[bin] ?? 0) + (lExo[bin] ?? 0);
      renderLadder(sum);
    }

    const corpCounts = new Map();
    for (const c of [...NewEdenJobsView.topCorps(50), ...ExordiumJobsView.topCorps(50, mainIds)]) {
      corpCounts.set(c.name, (corpCounts.get(c.name) ?? 0) + c.count);
    }
    renderCorps([...corpCounts.entries()]
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 8));

    const exo = ExordiumJobsView.stats();
    $("dash-neweden-count").textContent = t("board_jobs", { n: fmtNum(main.count) });
    $("dash-exordium-count").textContent = t("board_jobs", { n: fmtNum(exo.count) });
  }

  async function prefetchDetails(onProgress) {
    await Promise.all([
      NewEdenJobsView.prefetchDetails(onProgress),
      ExordiumJobsView.prefetchDetails(onProgress)
    ]);
  }

  async function prefetchPrices(onProgress) {
    await Promise.all([
      NewEdenJobsView.prefetchPrices(onProgress),
      ExordiumJobsView.prefetchPrices(onProgress)
    ]);
  }

  return { load, render, prefetchDetails, prefetchPrices };
})();

const App = (() => {
  const TABS = {
    dashboard: { view: DashboardView,   panel: "panel-dashboard" },
    "new-eden": { view: NewEdenJobsView, panel: "panel-new-eden" },
    exordium:   { view: ExordiumJobsView, panel: "panel-exordium" },
    faq:        { view: FaqView,          panel: "panel-faq" }
  };

  let activeTab = "dashboard";
  const loaded = new Set();
  let autoTimer = null;
  let lastUpdated = null;

  const $ = (id) => document.getElementById(id);

  function renderTimestamp() {
    if (!lastUpdated) return;
    $("timestamp").textContent = t("ts_label") + " " + fmtTime(lastUpdated);
  }

  function showPanel(tabId) {
    for (const [id, tab] of Object.entries(TABS)) {
      $(tab.panel).classList.toggle("hidden", id !== tabId);
      const link = $("tab-" + id);
      link.classList.toggle("active", id === tabId);
      if (id === tabId) link.setAttribute("aria-current", "page");
      else link.removeAttribute("aria-current");
    }
  }

  function setStatus(state, message = "") {
    $("error").classList.toggle("hidden", state !== "error");
    if (state === "error") $("error").textContent = message;
  }

  function reportError(err) {
    const hint = err && err.rateLimited ? t("err_rate_limit") : t("err_hint");
    setStatus("error", t("err_prefix") + (err?.message ?? err) + ". " + hint);
  }

  /* Background enrichment (per-job detail, then Jita/Manifest prices) — runs
     after the base list is already on screen, so it never blocks the
     initial render. A rate limit here just stops enrichment early; the base
     board stays usable. No-op for FaqView. */
  async function enrich(view) {
    try {
      await view.prefetchDetails((done, total) => {
        if (done % 10 === 0 || done === total) view.render();
      });
      view.render();
      await view.prefetchPrices((done, total) => {
        if (done % 5 === 0 || done === total) view.render();
      });
      view.render();
    } catch (err) {
      view.render();
      if (!err.rateLimited) reportError(err);
    }
  }

  async function runTab(tabId, force = false) {
    activeTab = tabId;
    showPanel(tabId);
    setStatus("idle"); // clear any error left over from a previous tab
    const tab = TABS[tabId];

    if (loaded.has(tabId) && !force) {
      tab.view.render();
      return;
    }

    try {
      await tab.view.load(force);
      loaded.add(tabId);
      tab.view.render();
      /* The board comes from the build's snapshot: show when it was
         fetched, not when this browser loaded it. */
      const stamp = await ESI.fetched("jobs");
      lastUpdated = stamp ? new Date(stamp) : new Date();
      renderTimestamp();
      setStatus("idle");
      enrich(tab.view);
    } catch (err) {
      reportError(err);
    }
  }

  /* No stored choice follows the system, like the Almanach. The button
     names what clicking switches *to*. */
  const systemLight = () => window.matchMedia("(prefers-color-scheme: light)").matches;
  function currentTheme() {
    return document.documentElement.dataset.theme || (systemLight() ? "light" : "dark");
  }
  function setTheme(theme) {
    if (theme) {
      document.documentElement.dataset.theme = theme;
      localStorage.setItem("fjb_theme", theme);
    }
    $("theme-toggle").textContent = currentTheme() === "dark" ? t("theme_light") : t("theme_dark");
  }

  function setAutoRefresh(on) {
    localStorage.setItem("fjb_auto_refresh", on ? "1" : "0");
    $("auto-refresh").setAttribute("aria-pressed", String(on));
    if (autoTimer) clearInterval(autoTimer);
    autoTimer = on
      ? setInterval(() => {
          loaded.delete(activeTab);
          runTab(activeTab, true);
        }, CONFIG.AUTO_REFRESH_MS)
      : null;
  }

  function init() {
    /* On a phone the filters sit behind a button, or they would fill the
       whole first screen before a single job shows. */
    document.addEventListener("click", (e) => {
      const btn = e.target.closest(".filters-toggle");
      if (!btn) return;
      const open = btn.closest(".board").classList.toggle("show-filters");
      btn.setAttribute("aria-expanded", String(open));
    });

    $("refresh").addEventListener("click", () => {
      loaded.delete(activeTab);
      runTab(activeTab, true);
    });
    $("auto-refresh").addEventListener("click", () => setAutoRefresh(!autoTimer));
    setAutoRefresh(localStorage.getItem("fjb_auto_refresh") === "1");

    $("theme-toggle").addEventListener("click", () => {
      setTheme(currentTheme() === "light" ? "dark" : "light");
    });
    setTheme(localStorage.getItem("fjb_theme"));

    applyI18n();
    const pageTab = document.body.dataset.tab;
    runTab(TABS[pageTab] ? pageTab : "dashboard");
  }

  return { init, runTab, reportError };
})();

document.addEventListener("DOMContentLoaded", App.init);
