/* Application bootstrap. Loaded before router.js, after every view script.
   Each page (/, /new-eden/, /exordium/, /faq/) is a real subpage shipping
   this same shell with every panel already in the DOM (see index.html) —
   only one is shown at a time. <body data-tab="..."> names the view the
   page shows on first load. router.js intercepts nav clicks after that and calls
   runTab() directly instead of letting the browser navigate, so board
   switches never reload the page; a real navigation (JS disabled, crawler,
   direct link) still lands on the matching static subpage generated by
   tools/build_pages.py. */
"use strict";

/* FAQ is static markup already in the DOM (no ESI data) — a no-op view so
   App can treat it exactly like the jobs boards. */
const FaqView = {
  load: async () => {},
  render() {},
  prefetchDetails: async () => {},
  prefetchPrices: async () => {}
};

/* The entry point to both boards: a ranked "grab this now" list, not a
   stats report. Loads both boards in parallel (not sequentially) so landing
   on the dashboard first never takes longer than the slower of the two —
   and once loaded, NewEdenJobsView/ExordiumJobsView don't re-fetch when
   their own tab is opened afterward (see jobs.js's `hasLoaded` guard). */
const DashboardView = (() => {
  const $ = (id) => document.getElementById(id);
  const TOP_N = 12;

  async function load(force = false) {
    await Promise.all([NewEdenJobsView.load(force), ExordiumJobsView.load(force)]);
  }

  /* The best paid jobs of both boards in one table, built from the same
     cells as the boards. A click opens the detail in place. */
  function renderDeals(deals) {
    const body = $("dash-deals");
    if (deals.length === 0) {
      body.innerHTML = Array.from({ length: TOP_N }, () => `<tr class="skeleton-row"><td></td><td></td><td></td><td></td><td></td></tr>`).join("");
      return;
    }
    body.innerHTML = deals.map(d => `<tr class="job-row" data-id="${esc(d.id)}" data-board="${d.board}" tabindex="0">${d.html}</tr>`).join("");
    if (!body.dataset.bound) {
      body.dataset.bound = "1";
      body.addEventListener("click", (e) => {
        const row = e.target.closest("tr.job-row");
        if (!row) return;
        const view = row.dataset.board === "exordium" ? ExordiumJobsView : NewEdenJobsView;
        view.toggleDetail(row, row.dataset.id);
      });
      body.addEventListener("keydown", (e) => {
        const row = e.target.closest("tr.job-row");
        if (!row || (e.key !== "Enter" && e.key !== " ")) return;
        e.preventDefault();
        const view = row.dataset.board === "exordium" ? ExordiumJobsView : NewEdenJobsView;
        view.toggleDetail(row, row.dataset.id);
      });
    }
  }

  function renderSecurity(counts) {
    const bar = $("dash-secbar");
    const legend = $("dash-seclegend");
    const total = counts.hs + counts.ls + counts.ns;
    if (total === 0) {
      bar.innerHTML = "";
      legend.innerHTML = "";
      return;
    }
    bar.innerHTML = ["hs", "ls", "ns"].map(cls =>
      counts[cls] > 0 ? `<span class="sec-${cls}" style="flex:${counts[cls]}"></span>` : ""
    ).join("");
    const colour = { hs: "var(--hs)", ls: "var(--ls)", ns: "var(--ns)" };
    legend.innerHTML = ["hs", "ls", "ns"].map(cls =>
      `<span><i style="background:${colour[cls]}"></i>${t("dash_sec_" + cls)}<b>${Math.round((counts[cls] / total) * 100)}%</b></span>`
    ).join("");
  }

  function renderCorps(corps) {
    const list = $("dash-corps");
    if (corps.length === 0) {
      list.innerHTML = "";
      return;
    }
    const max = corps[0].count;
    list.innerHTML = corps.map(c => `
      <li>
        <span class="cname">${esc(c.name)}</span>
        <span><span class="bar" style="display:block;width:${Math.max(6, Math.round((c.count / max) * 100))}%"></span></span>
        <span class="n">${fmtNum(c.count)}</span>
      </li>
    `).join("");
  }

  function render() {
    /* The totals count every job once. A job broadcast from both sides of
       the Exordium gap appears on both boards (31 of 383 on 5.10.2026), so
       Exordium only contributes the jobs New Eden doesn't already have.
       The two board cards below keep their own full counts — that is what
       each board shows. */
    const mainIds = NewEdenJobsView.scopedIds();
    const main = NewEdenJobsView.stats();
    const exoOnly = ExordiumJobsView.stats(mainIds);

    const priceableCount = main.priceableCount + exoOnly.priceableCount;
    const belowMarketCount = main.belowMarketCount + exoOnly.belowMarketCount;
    $("dash-active").textContent = fmtNum(main.count + exoOnly.count);
    $("dash-isk").textContent = fmtIsk(main.totalReward + exoOnly.totalReward) + " ISK";
    $("dash-below").textContent = priceableCount > 0 ? Math.round((belowMarketCount / priceableCount) * 100) + "%" : t("dash_pending");

    const deals = [
      ...NewEdenJobsView.topPayouts(TOP_N).map(j => ({ ...j, board: "main" })),
      ...ExordiumJobsView.topPayouts(TOP_N, mainIds).map(j => ({ ...j, board: "exordium" }))
    ].sort((a, b) => b.reward - a.reward).slice(0, TOP_N);
    renderDeals(deals);

    const secMain = NewEdenJobsView.securityBreakdown();
    const secExo = ExordiumJobsView.securityBreakdown(mainIds);
    renderSecurity({
      hs: secMain.hs + secExo.hs,
      ls: secMain.ls + secExo.ls,
      ns: secMain.ns + secExo.ns
    });

    const corpCounts = new Map();
    for (const c of [...NewEdenJobsView.topCorps(50), ...ExordiumJobsView.topCorps(50, mainIds)]) {
      corpCounts.set(c.name, (corpCounts.get(c.name) ?? 0) + c.count);
    }
    const topCorps = [...corpCounts.entries()]
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 8);
    renderCorps(topCorps);

    const exo = ExordiumJobsView.stats();
    $("dash-neweden-count").textContent = fmtNum(main.count);
    $("dash-neweden-isk").textContent = fmtIsk(main.totalReward) + " ISK";
    $("dash-exordium-count").textContent = fmtNum(exo.count);
    $("dash-exordium-isk").textContent = fmtIsk(exo.totalReward) + " ISK";
  }

  async function prefetchDetails(onProgress) {
    await Promise.all([
      NewEdenJobsView.prefetchDetails(onProgress),
      ExordiumJobsView.prefetchDetails(onProgress)
    ]);
  }

  async function prefetchPrices(onProgress) {
    await Promise.all([
      NewEdenJobsView.prefetchPrices(onProgress),
      ExordiumJobsView.prefetchPrices(onProgress)
    ]);
  }

  return { load, render, prefetchDetails, prefetchPrices };
})();

const App = (() => {
  const TABS = {
    dashboard: { view: DashboardView,   panel: "panel-dashboard" },
    "new-eden": { view: NewEdenJobsView, panel: "panel-new-eden" },
    exordium:   { view: ExordiumJobsView, panel: "panel-exordium" },
    faq:        { view: FaqView,          panel: "panel-faq" }
  };

  let activeTab = "dashboard";
  const loaded = new Set();
  let autoTimer = null;
  let lastUpdated = null;

  const $ = (id) => document.getElementById(id);

  function renderTimestamp() {
    if (!lastUpdated) return;
    $("timestamp").textContent = t("ts_label") + " " + lastUpdated.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "UTC" }) + " UTC";
  }

  function showPanel(tabId) {
    for (const [id, tab] of Object.entries(TABS)) {
      $(tab.panel).classList.toggle("hidden", id !== tabId);
      $("tab-" + id).classList.toggle("active", id === tabId);
    }
  }

  function setStatus(state, message = "") {
    $("error").classList.toggle("hidden", state !== "error");
    if (state === "error") $("error").textContent = message;
  }

  function reportError(err) {
    const hint = err && err.rateLimited ? t("err_rate_limit") : t("err_hint");
    setStatus("error", t("err_prefix") + (err?.message ?? err) + " — " + hint);
  }

  /* Background enrichment (per-job detail, then Jita/Manifest prices) — runs
     after the base list is already on screen, so it never blocks the
     initial render. A rate limit here just stops enrichment early; the base
     board stays usable. No-op for FaqView. */
  async function enrich(view) {
    try {
      await view.prefetchDetails((done, total) => {
        if (done % 10 === 0 || done === total) view.render();
      });
      view.render();
      await view.prefetchPrices((done, total) => {
        if (done % 5 === 0 || done === total) view.render();
      });
      view.render();
    } catch (err) {
      view.render();
      if (!err.rateLimited) reportError(err);
    }
  }

  async function runTab(tabId, force = false) {
    activeTab = tabId;
    showPanel(tabId);
    setStatus("idle"); // clear any error left over from a previous tab
    const tab = TABS[tabId];

    if (loaded.has(tabId) && !force) {
      tab.view.render();
      return;
    }

    try {
      await tab.view.load(force);
      loaded.add(tabId);
      tab.view.render();
      /* The board comes from the build's snapshot: show when it was
         fetched, not when this browser loaded it. */
      const stamp = await ESI.fetched("jobs");
      lastUpdated = stamp ? new Date(stamp) : new Date();
      renderTimestamp();
      setStatus("idle");
      enrich(tab.view);
    } catch (err) {
      reportError(err);
    }
  }

  /* No stored choice follows the system, like the Almanach. The button
     names what clicking switches *to*. */
  const systemLight = () => window.matchMedia("(prefers-color-scheme: light)").matches;
  function currentTheme() {
    return document.documentElement.dataset.theme || (systemLight() ? "light" : "dark");
  }
  function setTheme(theme) {
    if (theme) {
      document.documentElement.dataset.theme = theme;
      localStorage.setItem("fjb_theme", theme);
    }
    $("theme-toggle").textContent = currentTheme() === "dark" ? t("theme_light") : t("theme_dark");
  }

  function setAutoRefresh(on) {
    localStorage.setItem("fjb_auto_refresh", on ? "1" : "0");
    $("auto-refresh").setAttribute("aria-pressed", String(on));
    if (autoTimer) clearInterval(autoTimer);
    autoTimer = on
      ? setInterval(() => {
          loaded.delete(activeTab);
          runTab(activeTab, true);
        }, CONFIG.AUTO_REFRESH_MS)
      : null;
  }

  function init() {
    /* On a phone the filters sit behind a button, or they would fill the
       whole first screen before a single job shows. */
    document.addEventListener("click", (e) => {
      const btn = e.target.closest(".filters-toggle");
      if (!btn) return;
      const open = btn.closest(".board").classList.toggle("show-filters");
      btn.setAttribute("aria-expanded", String(open));
    });

    $("refresh").addEventListener("click", () => {
      loaded.delete(activeTab);
      runTab(activeTab, true);
    });
    $("auto-refresh").addEventListener("click", () => setAutoRefresh(!autoTimer));
    setAutoRefresh(localStorage.getItem("fjb_auto_refresh") === "1");

    $("theme-toggle").addEventListener("click", () => {
      setTheme(currentTheme() === "light" ? "dark" : "light");
    });
    setTheme(localStorage.getItem("fjb_theme"));

    applyI18n();
    const pageTab = document.body.dataset.tab;
    runTab(TABS[pageTab] ? pageTab : "dashboard");
  }

  return { init, runTab, reportError };
})();

document.addEventListener("DOMContentLoaded", App.init);
