/* Generated from tools/build_pages.py's PAGES list. Do not edit by hand.
   Route table for js/router.js (soft navigation between boards). */
"use strict";

const ROUTES = {
  "/": {"tab": "dashboard", "lang": "en", "title": "Freelancer: EVE Online freelance jobs", "description": "Every open Freelance Job in EVE Online by security status, the best paid jobs right now, and who is hiring, across New Eden and Exordium.", "canonical": "https://freelancer.tonicdock.com/", "alt": "/de/", "altCanonical": "https://freelancer.tonicdock.com/de/"},
  "/new-eden/": {"tab": "new-eden", "lang": "en", "title": "New Eden freelance jobs: Freelancer", "description": "All EVE Online freelance jobs in New Eden: sort by reward, filter by type, region and distance, and compare the reward with market prices.", "canonical": "https://freelancer.tonicdock.com/new-eden/", "alt": "/de/new-eden/", "altCanonical": "https://freelancer.tonicdock.com/de/new-eden/"},
  "/exordium/": {"tab": "exordium", "lang": "en", "title": "Exordium freelance jobs: Freelancer", "description": "All EVE Online freelance jobs in Exordium, the starter region with its own board and its own reference market in Manifest.", "canonical": "https://freelancer.tonicdock.com/exordium/", "alt": "/de/exordium/", "altCanonical": "https://freelancer.tonicdock.com/de/exordium/"},
  "/faq/": {"tab": "faq", "lang": "en", "title": "Questions: Freelancer", "description": "How the Freelancer board works: data source, the value check against market prices, location and distance, the New Eden and Exordium split, and privacy.", "canonical": "https://freelancer.tonicdock.com/faq/", "alt": "/de/faq/", "altCanonical": "https://freelancer.tonicdock.com/de/faq/"},
  "/de/": {"tab": "dashboard", "lang": "de", "title": "Freelancer: Freelance-Aufträge in EVE Online", "description": "Jeder offene Freelance-Auftrag in EVE Online nach Sicherheitsstatus, die bestbezahlten Aufträge und wer sie vergibt, in New Eden und Exordium.", "canonical": "https://freelancer.tonicdock.com/de/", "alt": "/", "altCanonical": "https://freelancer.tonicdock.com/"},
  "/de/new-eden/": {"tab": "new-eden", "lang": "de", "title": "Freelance-Aufträge in New Eden: Freelancer", "description": "Alle Freelance-Aufträge in New Eden: nach Belohnung sortieren, nach Art, Region und Entfernung filtern und die Belohnung mit Marktpreisen vergleichen.", "canonical": "https://freelancer.tonicdock.com/de/new-eden/", "alt": "/new-eden/", "altCanonical": "https://freelancer.tonicdock.com/new-eden/"},
  "/de/exordium/": {"tab": "exordium", "lang": "de", "title": "Freelance-Aufträge in Exordium: Freelancer", "description": "Alle Freelance-Aufträge in Exordium, dem Startgebiet mit eigenem Brett und eigenem Referenzmarkt in Manifest.", "canonical": "https://freelancer.tonicdock.com/de/exordium/", "alt": "/exordium/", "altCanonical": "https://freelancer.tonicdock.com/exordium/"},
  "/de/faq/": {"tab": "faq", "lang": "de", "title": "Fragen: Freelancer", "description": "Wie das Freelancer-Brett funktioniert: Datenquelle, Abgleich mit Marktpreisen, Ort und Entfernung, die Trennung von New Eden und Exordium, Datenschutz.", "canonical": "https://freelancer.tonicdock.com/de/faq/", "alt": "/faq/", "altCanonical": "https://freelancer.tonicdock.com/faq/"}
};
