#!/usr/bin/env python3
"""Generate js/data/staticdata.js from the EVE SDE (JSONL zip).

Produces the k-space stargate adjacency graph and system/region names for
every k-space solar system (not just a subset) — used for the "distance
from home" jump count and region lookup on job broadcast locations.

Usage:
  python tools/build_static_data.py <path-to-sde-jsonl-zip>

Stdlib only, no network access.
"""
import io
import json
import sys
import zipfile
from pathlib import Path

OUT_PATH = Path(__file__).resolve().parent.parent / "js" / "data" / "staticdata.js"

# Wormhole/abyssal/void regions start at 11000000; k-space regions are below.
KSPACE_REGION_MAX = 11000000


def read_jsonl(zf, name):
    with zf.open(name) as fh:
        for line in io.TextIOWrapper(fh, encoding="utf-8"):
            line = line.strip()
            if line:
                yield json.loads(line)


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: build_static_data.py <sde-jsonl-zip>")
    zip_path = Path(sys.argv[1])
    if not zip_path.exists():
        sys.exit(f"SDE zip not found: {zip_path}")

    with zipfile.ZipFile(zip_path) as zf:
        meta = next(read_jsonl(zf, "_sde.jsonl"))

        region_names = {}
        for r in read_jsonl(zf, "mapRegions.jsonl"):
            region_names[r["_key"]] = r["name"]["en"]

        systems = {}
        for s in read_jsonl(zf, "mapSolarSystems.jsonl"):
            if s["regionID"] >= KSPACE_REGION_MAX:
                continue
            systems[s["_key"]] = {
                "name": s["name"]["en"],
                "region": region_names.get(s["regionID"], "?"),
            }

        graph = {sid: [] for sid in systems}
        for g in read_jsonl(zf, "mapStargates.jsonl"):
            a = g["solarSystemID"]
            b = g["destination"]["solarSystemID"]
            if a in graph and b in systems and b not in graph[a]:
                graph[a].append(b)

    names = {sid: s["name"] for sid, s in systems.items()}
    regions = {sid: s["region"] for sid, s in systems.items()}

    payload = {
        "build": meta.get("buildNumber"),
        "released": meta.get("releaseDate"),
        "names": names,
        "regions": regions,
        "graph": graph,
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    OUT_PATH.write_text(
        "/* Generated by tools/build_static_data.py — do not edit by hand.\n"
        f" * SDE build {payload['build']} ({payload['released']}). */\n"
        "\"use strict\";\n"
        f"const SDATA = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT_PATH} ({OUT_PATH.stat().st_size // 1024} KiB)")
    print(f"systems: {len(names)}, regions: {len(set(regions.values()))}")


if __name__ == "__main__":
    main()
